Added some CI and CD test cases

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,6 +1,8 @@
 stages:
+  - test-ci
   - build
   - deploy
+  - test-cd
 
 variables:
   DOCKER_FILE: "Dockerfile"
@@ -10,6 +12,20 @@ variables:
   DOCKER_TLS_CERTDIR: ""
   DOCKER_IMAGE_NAME: "bbertka/stock-flask-app"  # Base image name
   DOCKER_BASE_TAG: "latest"  # Base tag
+
+local-test:
+  stage: test-ci
+  image: python:3.8  
+  script:
+    - pip3 install -r requirements.txt  # Install dependencies
+    - python3 src/app.py &  # Start app in the background
+    - sleep 5  # Give Flask some time to start
+    - >
+      curl --fail http://localhost:5000/stock-price?symbol=AAPL
+      || (echo "Test failed" && exit 1)
+    - kill $!  # Stop the Flask app
+  only:
+    - main
 
 build-amd64:
   stage: build
@@ -59,5 +75,22 @@ deploy-k3s:
     - kubectl apply -f deployment.yml
     - DEPLOYMENT_NAME=$(grep 'name:' deployment.yml | awk 'NR==1{print $2}')
     - kubectl rollout restart deployment/$DEPLOYMENT_NAME -n $KUBE_NAMESPACE
+  only:
+    - main
+
+remote-test:
+  stage: test-cd
+  image: appropriate/curl  # Using a lightweight image with curl installed
+  script:
+    - >
+      response=$(curl -s "http://$APP_IP_ADDRESS/stock-price?symbol=AAPL")
+    - echo "Response: $response"
+    - |
+      if echo "$response" | grep -q '"symbol": "AAPL"'; then
+        echo "Test Passed: AAPL stock price retrieved successfully."
+      else
+        echo "Test Failed: AAPL stock price not found in response."
+        exit 1
+      fi
   only:
     - main
